### PR TITLE
Migrate commit from PowerShel/PowerShell  

### LINKED ISSUE #4: Need port merged commit from PowerShell/PowerShell repo
Need port https://github.com/PowerShell/PowerShell/pull/7218

### PR DESCRIPTION
**Pull request by iSazonov**
Fix #4 

Migrate commit from PowerShel/PowerShell  [Build: Fix a check to avoid null argument in case 'vcvarsall.bat' is absent (#7218)](https://github.com/PowerShell/PowerShell/pull/7218)

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@iSazonov  Could you please rebase?

**Comment by iSazonov** [comment]
@adityapatwardhan Done!

**Comment by adityapatwardhan** [comment]
@iSazonov  I rebased and pushed. The CI is enabled now so we have validation for taking in changes.

**Comment by iSazonov** [comment]
Should I fix something?

**Comment by adityapatwardhan** [comment]
@iSazonov At this moment no. I have made some more fixes to the CI. When they are merged I will rebase.

**Pull request merged**
